{
 "title": "NestJS Logs Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "query": "label_values(appName)" }
  ]
 },
 "panels": [
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{appName=\"$app\"} | json | label_format level=\"{{.levelName}}\" | line_format \"[{{.ctx}}] {{.msg}} [traceId: {{.traceId}}] {{.timestamp}}\""
    }
   ]
  },
  {
   "title": "Logs per Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({appName=\"$app\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Errors Only",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{appName=\"$app\"} | json | levelName=\"error\""
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{appName=\"$app\"} |= \"method\""
    }
   ]
  }
 ]
}